; =============================================================
; Codebook Ingestion — Pod 3.8 D3.31
;
; Substrate-private boot-time helper. Reads CBKBOK01 codebook image
; embedded at codebook_image_start (boot/codebook_data.asm; auto-
; generated by tools/codebook_builder.py at every build), validates
; magic + dim + scalar_type, iterates count entries, forges an
; embedding for each via the canonical Pod 3 forge sequence with
; imported provenance tuple pre-stamped at vm_embedding_imported.
;
; D3.31: not bytecode-dispatched. Runs at boot between cap-substrate
; init and bastian dispatch (efi_entry calls boot_ingest_codebook
; post-verify_root_cap_mac per Pod 3.8.F). Under implicit ROOT_CAP
; context (current_cap_id=1 from boot init). 0j per D3.10 substrate-
; bookkeeping doctrine — no .construct_ok_outcome wrap, no babylon
; ripple, no per-op cost-table drain.
;
; Failure modes (all hard-fail with status write to vm_codebook_meta +
; auryn_puts diagnostic + cli/hlt/jmp $; mirrors verify_root_cap_mac E3
; pattern from boot/cap.asm):
;   - magic mismatch:           CBK_STATUS_ERR_BAD_MAGIC
;   - dim != EMBEDDING_DIM:     CBK_STATUS_ERR_BAD_DIM
;   - scalar_type != f32:       CBK_STATUS_ERR_BAD_DIM
;   - embedding_pool exhausted: CBK_STATUS_ERR_POOL_FULL
;
; On success: writes vm_codebook_meta with count, dim, scalar_type,
; status=CBK_STATUS_SUCCESS, payload_hash (16 bytes from header).
; Empty codebook (count=0; default when no inputs/codebook.txt) skips
; the loop and writes meta with status=success — substrate boots clean
; with vm_embedding_next staying at 0; prior-pod canary IDs unaffected.
;
; Inline allocator: bump-allocator vs vm_embedding_pool / vm_embedding_next
; (mirrors cbs_vm.asm .embedding_alloc local; substrate-private path
; does not call the dot-prefixed handler-local helper).
;
; Input:    none (reads codebook_image_start extern + substrate state)
; Output:   none (side effects: embedding_pool populated; embedding_registry
;           populated; vm_embedding_imported tuples written; vm_codebook_meta
;           updated)
; Clobbers: rax, rcx, rdx, rsi, rdi, r8-r11
; Preserves: rbx, rbp, r12-r15 (substrate convention; saved/restored
;            via push/pop bracket)
; =============================================================

global boot_ingest_codebook

boot_ingest_codebook:
    push    rbx
    push    rbp
    push    r12
    push    r13
    push    r14
    push    r15

    ; rbx = codebook image header base (preserved across helper body)
    lea     rbx, [rel codebook_image_start]

    ; --- Step 1: Validate magic == CBK_MAGIC_QWORD ---
    mov     rax, [rbx + CBK_HEADER_OFF_MAGIC]
    mov     rcx, CBK_MAGIC_QWORD
    cmp     rax, rcx
    jne     .fatal_bad_magic

    ; --- Step 2: Validate dim == EMBEDDING_DIM ---
    mov     rax, [rbx + CBK_HEADER_OFF_DIM]
    cmp     rax, EMBEDDING_DIM
    jne     .fatal_bad_dim

    ; --- Step 2b: Validate scalar_type == CBK_SCALAR_TYPE_F32 (==0) ---
    mov     eax, [rbx + CBK_HEADER_OFF_SCALAR_TYPE]
    test    eax, eax
    jnz     .fatal_bad_dim

    ; --- Step 3: Read count → r12 ---
    mov     r12, [rbx + CBK_HEADER_OFF_COUNT]

    ; --- Step 4: Compute vector block base → r13 ---
    mov     rax, [rbx + CBK_HEADER_OFF_VECTOR_BLOCK_OFFSET]
    lea     r13, [rbx + rax]                      ; r13 = absolute address of first vector

    ; Empty codebook (count=0) → skip loop, write meta with status=success
    test    r12, r12
    jz      .write_meta

    ; --- Step 5: Iterate i in 0..count-1 ---
    xor     r14, r14                              ; r14 = i (loop index)
.ingest_loop:
    cmp     r14, r12
    jge     .write_meta

    ; Pool capacity check (defensive; embedding_pool exhaustion = FATAL)
    mov     rcx, [rel vm_embedding_next]
    cmp     rcx, EMBEDDING_POOL_SLOTS
    jge     .fatal_pool_full

    ; Inline alloc: r15 = vm_embedding_pool + (vm_embedding_next * EMBEDDING_SLOT_BYTES)
    imul    rax, rcx, EMBEDDING_SLOT_BYTES
    lea     r15, [rel vm_embedding_pool]
    add     r15, rax                              ; r15 = dest slot_ptr (preserved across loop body)
    inc     qword [rel vm_embedding_next]

    ; Write placeholder id (0) + cap-cache (ROOT arena/owner/creator)
    mov     qword [r15 + EMBEDDING_OFF_ID_SELF], 0
    mov     rax, [rel current_cap_arena_id_cache]
    mov     [r15 + EMBEDDING_OFF_ARENA_ID], rax
    mov     rax, [rel current_cap_owner_demod_id_cache]
    mov     [r15 + EMBEDDING_OFF_OWNER_DEMOD_ID], rax
    mov     rax, [rel current_cap_id]
    mov     [r15 + EMBEDDING_OFF_CREATOR_CAP_ID], rax

    ; rep movsb 1536-byte vector: src = r13 + i*EMBEDDING_VECTOR_BYTES; dst = r15 + EMBEDDING_OFF_VECTOR
    imul    rsi, r14, EMBEDDING_VECTOR_BYTES
    add     rsi, r13                              ; rsi = src vector address
    lea     rdi, [r15 + EMBEDDING_OFF_VECTOR]     ; rdi = dst vector address
    mov     rcx, EMBEDDING_VECTOR_BYTES           ; 1536
    cld
    rep     movsb

    ; Register slot to obtain embedding_id (R7 ordering: post-content-write)
    mov     rdi, r15
    call    registry_register_embedding           ; rax = embedding_id (0 if registry full); rdi preserved
    test    rax, rax
    jz      .fatal_pool_full                       ; defensive — pool/registry should stay in sync

    ; Stamp embedding_id_self post-registry (R7-corrected ordering per Pod 3)
    mov     [r15 + EMBEDDING_OFF_ID_SELF], rax

    ; SipHash MAC over 196 qwords (header 4 + vector 192) per D3.3
    push    rax                                   ; preserve embedding_id across siphash
    mov     rdi, r15
    mov     rsi, EMBEDDING_MAC_INPUT_QWORDS       ; 196
    call    siphash_compute                       ; rax = MAC; rdi preserved per siphash contract
    mov     [r15 + EMBEDDING_OFF_MAC], rax        ; stamp MAC at +0x620
    pop     rax                                   ; restore embedding_id

    ; Imported-tuple write at vm_embedding_imported + (id-1) * IMPORTED_TUPLE_BYTES
    ; Tuple shape (D3.27 Layout-2 mirror): (codebook_id=1, line_index=i, reserved_hash=0, reserved_timestamp=0)
    lea     rdx, [rel vm_embedding_imported]
    mov     rcx, rax
    dec     rcx
    shl     rcx, 5                                ; * 32 (IMPORTED_TUPLE_BYTES)
    add     rdx, rcx                              ; rdx = tuple base addr
    mov     qword [rdx + IMPORTED_TUPLE_OFF_CODEBOOK_ID],        1   ; V1.0 single-codebook
    mov     [rdx + IMPORTED_TUPLE_OFF_LINE_INDEX], r14            ; original index in codebook
    mov     qword [rdx + IMPORTED_TUPLE_OFF_RESERVED_HASH],      0
    mov     qword [rdx + IMPORTED_TUPLE_OFF_RESERVED_TIMESTAMP], 0

    inc     r14
    jmp     .ingest_loop

.write_meta:
    ; Success path: write vm_codebook_meta with header-derived state + status
    lea     rax, [rel vm_codebook_meta]
    mov     [rax + CBK_META_OFF_COUNT], r12       ; count from header (validated path)
    mov     rcx, [rbx + CBK_HEADER_OFF_DIM]
    mov     [rax + CBK_META_OFF_DIM], rcx
    mov     ecx, [rbx + CBK_HEADER_OFF_SCALAR_TYPE]   ; 32-bit; zero-extends to 64
    mov     [rax + CBK_META_OFF_SCALAR_TYPE], rcx
    mov     qword [rax + CBK_META_OFF_INGESTION_STATUS], CBK_STATUS_SUCCESS

    ; Copy 16-byte payload_hash from header to meta cache (two qword copies)
    mov     rcx, [rbx + CBK_HEADER_OFF_PAYLOAD_HASH]
    mov     [rax + CBK_META_OFF_PAYLOAD_HASH], rcx
    mov     rcx, [rbx + CBK_HEADER_OFF_PAYLOAD_HASH + 8]
    mov     [rax + CBK_META_OFF_PAYLOAD_HASH + 8], rcx

    pop     r15
    pop     r14
    pop     r13
    pop     r12
    pop     rbp
    pop     rbx
    ret

; --- FATAL paths: write status + diagnostic + cli/hlt/jmp $ infinite loop ---
; Mirrors boot/cap.asm verify_root_cap_mac E3 hard-fail pattern. No return.

.fatal_bad_magic:
    lea     rax, [rel vm_codebook_meta]
    mov     qword [rax + CBK_META_OFF_INGESTION_STATUS], CBK_STATUS_ERR_BAD_MAGIC
    lea     rsi, [rel str_codebook_bad_magic]
    call    auryn_puts
    cli
    hlt
.fatal_bad_magic_hang:
    jmp     .fatal_bad_magic_hang

.fatal_bad_dim:
    lea     rax, [rel vm_codebook_meta]
    mov     qword [rax + CBK_META_OFF_INGESTION_STATUS], CBK_STATUS_ERR_BAD_DIM
    lea     rsi, [rel str_codebook_bad_dim]
    call    auryn_puts
    cli
    hlt
.fatal_bad_dim_hang:
    jmp     .fatal_bad_dim_hang

.fatal_pool_full:
    lea     rax, [rel vm_codebook_meta]
    mov     qword [rax + CBK_META_OFF_INGESTION_STATUS], CBK_STATUS_ERR_POOL_FULL
    lea     rsi, [rel str_codebook_pool_full]
    call    auryn_puts
    cli
    hlt
.fatal_pool_full_hang:
    jmp     .fatal_pool_full_hang

; --- Diagnostic strings (substrate-permanent at boot_ingest_codebook scope) ---
str_codebook_bad_magic:    db "[FATAL] codebook: bad magic (CBKBOK01 expected)", 10, 0
str_codebook_bad_dim:      db "[FATAL] codebook: bad dim or scalar_type", 10, 0
str_codebook_pool_full:    db "[FATAL] codebook: embedding_pool exhausted before count satisfied", 10, 0
