; Pod 3.8 codebook image - auto-generated by tools/codebook_builder.py
; Format: CBKBOK01 (incbin-form embed; binary at /mnt/c/Users/Rando/codebook/boot/codebook_data.bin)
; DO NOT EDIT - regenerate by re-running codebook_builder.py

    align 16
codebook_image_start:
    incbin "/mnt/c/Users/Rando/codebook/boot/codebook_data.bin"
codebook_image_end:

; Image total: 64 bytes (64-byte header + 0-byte vector block)
